// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhx7Sq1jU5W-4RYc5gDzxmJvEe0MbvTng',
    appId: '1:102233149888:web:3a38f72608a6777b1f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    authDomain: 'sokoflow-5d830.firebaseapp.com',
    storageBucket: 'sokoflow-5d830.appspot.com',
    measurementId: 'G-DKNCNCPMMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZoyva4tvBBYqi6JQ6EY6b9-4LGa_ykw',
    appId: '1:102233149888:android:68efd6daf22f50241f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    storageBucket: 'sokoflow-5d830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhfBRBHk-9kBg5i3cf5gtueVK3ru9LE8',
    appId: '1:102233149888:ios:0ae7a3a04d6e17111f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    storageBucket: 'sokoflow-5d830.appspot.com',
    androidClientId: '102233149888-sudt10t9enr2vo0llvahgqbrs5uf8aqg.apps.googleusercontent.com',
    iosClientId: '102233149888-nosk5b9q16n5vm2sknc3o01e3mtk8uj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoflowalpine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhx7Sq1jU5W-4RYc5gDzxmJvEe0MbvTng',
    appId: '1:102233149888:web:3a38f72608a6777b1f7825',
    messagingSenderId: '102233149888',
    projectId: 'sokoflow-5d830',
    authDomain: 'sokoflow-5d830.firebaseapp.com',
    storageBucket: 'sokoflow-5d830.appspot.com',
    measurementId: 'G-DKNCNCPMMD',
  );

}